FROM node:22-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm@11.22.0
COPY . .
RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @karigar/worker build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN npm install -g pnpm@11.22.0
COPY --from=builder /app /app
CMD ["pnpm", "--filter", "@karigar/worker", "start"]
